### PR TITLE
Fixed: Responsiveness for mobile devices w.r.t to side navigation

### PR DESCRIPTION
**Pull request by patelvimal**
- Responsivess for mobile devices
- Angular 12 migration
- UI design enhancement with respect to search bar

Current Design:-
Capture1

Proposed Design:-
CPT2105292345-467x610

### CODE REVIEW

**Comment by santoshyadavdev** [comment]
Thanks @patelvimal there is some node version issue on netlify, I am looking into it.

**Comment by patelvimal** [comment]
> Thanks @patelvimal there is some node version issue on netlify, I am looking into it.

No issues, take your time. There are some more improvement we can do in this site, including adding the relevant blogs and tutorials for angular builders. Will work on that when I get time., thanks.

**Comment by santoshyadavdev** [comment]
> > Thanks @patelvimal there is some node version issue on netlify, I am looking into it.
> 
> No issues, take your time. There are some more improvement we can do in this site, including adding the relevant blogs and tutorials for angular builders. Will work on that when I get time., thanks.

Was able to resolve and merge 😃

**Comment by patelvimal** [comment]
> > > Thanks @patelvimal there is some node version issue on netlify, I am looking into it.
> > 
> > 
> > No issues, take your time. There are some more improvement we can do in this site, including adding the relevant blogs and tutorials for angular builders. Will work on that when I get time., thanks.
> 
> Was able to resolve and merge 😃

:thumbsup: :thumbsup: once it is deployed let me know, will test it also on live environment.

**Comment by santoshyadavdev** [comment]
Its deployed and working as expected.

**Pull request merged**
